// Vendors the @mygpt/sdk OpenAPI spec into this docs repo so the deployed
// site (GitHub Pages, which only checks out MGA-Docs) can render it.
//
// Source of truth is the main app repo, generated by `pnpm sdk:refresh`:
//   ../mygptassistants/packages/sdk/openapi-spec.json
//
// Run locally after the SDK spec changes, then commit the updated JSON:
//   npm run sync:openapi
//
// This is a LOCAL dev convenience only — CI never runs it. The committed
// copy at src/openapi/mga-sdk.json is what gets built & deployed.

import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(__dirname, '..');

// The main app repo lives as a sibling of this docs repo.
const SOURCE = resolve(repoRoot, '../mygptassistants/packages/sdk/openapi-spec.json');
const DEST = resolve(repoRoot, 'src/openapi/mga-sdk.json');

// The generated spec ships with a localhost server (extracted in-process in
// CI). Rewrite it to the real public API base so the reference shows the URLs
// consumers actually call.
const PUBLIC_SERVER = {
  url: 'https://api.mygptassistants.com/api/v1',
  description: 'Production',
};

let raw;
try {
  raw = readFileSync(SOURCE, 'utf8');
} catch (err) {
  console.error(`\n✗ Could not read the SDK spec at:\n    ${SOURCE}\n`);
  console.error(
    'This script expects the main app repo (mygptassistants) to sit next to\n' +
      'this docs repo. Clone it as a sibling, then run `pnpm sdk:refresh` there\n' +
      'to (re)generate packages/sdk/openapi-spec.json before syncing.\n',
  );
  process.exit(1);
}

const spec = JSON.parse(raw);

spec.servers = [PUBLIC_SERVER];
spec.info = {
  ...spec.info,
  title: 'MyGPTAssistants SDK & REST API',
};

mkdirSync(dirname(DEST), { recursive: true });
writeFileSync(DEST, JSON.stringify(spec, null, 2) + '\n');

const pathCount = Object.keys(spec.paths ?? {}).length;
let opCount = 0;
for (const item of Object.values(spec.paths ?? {})) {
  opCount += Object.keys(item).filter((m) =>
    ['get', 'post', 'put', 'patch', 'delete'].includes(m),
  ).length;
}

console.log(
  `✓ Synced OpenAPI spec → src/openapi/mga-sdk.json ` +
    `(${pathCount} paths, ${opCount} operations)`,
);
